spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dsc_staff
    username: postgres
    password: dscpassword
    driver-class-name: org.postgresql.Driver

    # HikariCP-specific properties (optional tuning)


    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000
      pool-name: HikariCP


  # Optional: JPA settings if using Spring Data JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
