spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database_name
    username: your_db_user
    password: your_db_password
    driver-class-name: org.postgresql.Driver

    # HikariCP-specific properties (optional tuning)
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariCP

  # Optional: JPA settings if using Spring Data JPA
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
